import {
  Accessibility,
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Banknote,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clapperboard,
  ClipboardCheck,
  Clock,
  Cloud,
  Code,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FlaskConical,
  Gamepad2,
  Gauge,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  Image,
  Info,
  Inbox,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LibraryBig,
  LineChart,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Mic,
  Monitor,
  Newspaper,
  Plane,
  Plug,
  Quote,
  RadioTower,
  Repeat,
  Scale,
  Search,
  Share2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Smartphone,
  Sparkles,
  Store,
  TestTubeDiagonal,
  TrendingDown,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  UsersRound,
  Video,
  WandSparkles,
  Webhook,
  Workflow,
  X,
  Menu,
  Plus,
  Minus,
  type LucideIcon,
} from 'lucide-react'

/**
 * Every Lucide glyph the site uses, keyed by the kebab-case name the content
 * modules and the design system speak.
 *
 * WHY A REGISTRY. The prototype loaded icons as CSS masks from a CDN, so any
 * name worked at runtime. `lucide-react` exports one component per icon, which
 * only tree-shakes if the import is static — `import * as icons` would pull the
 * entire 1,500-icon set into the bundle, and the `DynamicIcon` helper is
 * client-only, which would push `"use client"` onto every card that shows an
 * icon.
 *
 * So: an explicit map. Adding an icon is one import plus one line here, and
 * TypeScript rejects a name that is not in the set.
 *
 * The list was extracted from the prototype's data files and component sources.
 */
export const ICON_REGISTRY = {
  accessibility: Accessibility,
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  banknote: Banknote,
  'book-open': BookOpen,
  bot: Bot,
  briefcase: Briefcase,
  'building-2': Building2,
  car: Car,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  clapperboard: Clapperboard,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  'flask-conical': FlaskConical,
  'gamepad-2': Gamepad2,
  gauge: Gauge,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  'heart-pulse': HeartPulse,
  image: Image,
  info: Info,
  inbox: Inbox,
  landmark: Landmark,
  languages: Languages,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'library-big': LibraryBig,
  'line-chart': LineChart,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'message-square': MessageSquare,
  mic: Mic,
  monitor: Monitor,
  newspaper: Newspaper,
  plane: Plane,
  plug: Plug,
  quote: Quote,
  'radio-tower': RadioTower,
  repeat: Repeat,
  scale: Scale,
  search: Search,
  'share-2': Share2,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  shuffle: Shuffle,
  smartphone: Smartphone,
  sparkles: Sparkles,
  store: Store,
  'test-tube-diagonal': TestTubeDiagonal,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  trophy: Trophy,
  'user-check': UserCheck,
  users: Users,
  'users-round': UsersRound,
  video: Video,
  'wand-sparkles': WandSparkles,
  webhook: Webhook,
  workflow: Workflow,
  // Mobile nav toggle — the source picks these with a ternary, so they do not
  // appear in a naive grep of the content data.
  x: X,
  menu: Menu,
  // FaqAccordion's open/closed affordance.
  plus: Plus,
  minus: Minus,
} as const satisfies Record<string, LucideIcon>

/** The kebab-case names this site can render. */
export type IconName = keyof typeof ICON_REGISTRY

export function isIconName(value: string): value is IconName {
  return value in ICON_REGISTRY
}
