'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { serverFetch } from '@/lib/api/server'
import { getUser } from '@/lib/auth/session'
import { formString, formTrimmed } from '@/lib/form-data'
import { parseCommaList } from '@/lib/admin/csv'

interface ProjectResponse {
  id: string
}

/**
 * Create a project on behalf of any organisation.
 *
 * The reference (`C4T-YYYY-NNNN`) is generated by the API from a database
 * sequence; the form does not collect it. The `createdById` is the admin
 * submitting the form, which the API records automatically. The form layout
 * mirrors the detail page so the "edit existing project" form is the same
 * fields minus the read-only metadata.
 *
 * Multi-value fields are collected as comma-separated text instead of one
 * input per tag — that is what the data really is, and a chip-input UI
 * would be client state for a Server Component form.
 */
export async function createProjectAction(formData: FormData): Promise<void> {
  await getUser()

  const startDate = formTrimmed(formData, 'startDate')
  const endDate = formTrimmed(formData, 'endDate')

  const body = {
    organisationId: formTrimmed(formData, 'organisationId') || undefined,
    title: formTrimmed(formData, 'title'),
    summary: formTrimmed(formData, 'summary') || undefined,
    instructions: formTrimmed(formData, 'instructions') || undefined,
    priority: formTrimmed(formData, 'priority') || 'NORMAL',
    platformTargets: parseCommaList(formString(formData, 'platformTargets')),
    targetCountries: parseCommaList(formString(formData, 'targetCountries')).map((c) =>
      c.toUpperCase(),
    ),
    targetLanguages: parseCommaList(formString(formData, 'targetLanguages')).map((l) =>
      l.toLowerCase(),
    ),
    ...(startDate ? { startDate } : {}),
    ...(endDate ? { endDate } : {}),
  }

  const { id } = await serverFetch<ProjectResponse>('projects', {
    method: 'POST',
    body,
  })

  revalidatePath('/app/admin/projects')
  redirect(`/app/admin/projects/${id}`)
}
