'use server'

import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { serverFetch } from '@/lib/api/server'
import { getUser } from '@/lib/auth/session'
import { formString, formTrimmed } from '@/lib/form-data'
import { parseCommaList } from '@/lib/admin/csv'

interface ProjectResponse {
  id: string
}

/** Just enough of the detail read to find the build the create just made. */
interface ProjectBuilds {
  builds?: readonly { id: string; isDefault: boolean }[]
}

/**
 * Create a project on behalf of any organisation.
 *
 * The reference (`C4T-YYYY-NNNN`) is generated by the API from a database
 * sequence; the form does not collect it. The `createdById` is the admin
 * submitting the form, which the API records automatically. The form layout
 * mirrors the detail page so the "edit existing project" form is the same
 * fields minus the read-only metadata.
 *
 * Multi-value fields are collected as comma-separated text instead of one
 * input per tag — that is what the data really is, and a chip-input UI
 * would be client state for a Server Component form.
 */
export async function createProjectAction(formData: FormData): Promise<void> {
  await getUser()

  const startDate = formTrimmed(formData, 'startDate')
  const endDate = formTrimmed(formData, 'endDate')
  const maxTesters = formTrimmed(formData, 'maxTesters')

  const body = {
    organisationId: formTrimmed(formData, 'organisationId') || undefined,
    title: formTrimmed(formData, 'title'),
    summary: formTrimmed(formData, 'summary') || undefined,
    instructions: formTrimmed(formData, 'instructions') || undefined,
    priority: formTrimmed(formData, 'priority') || 'NORMAL',
    platformTargets: parseCommaList(formString(formData, 'platformTargets')),
    targetCountries: parseCommaList(formString(formData, 'targetCountries')).map((c) =>
      c.toUpperCase(),
    ),
    targetLanguages: parseCommaList(formString(formData, 'targetLanguages')).map((l) =>
      l.toLowerCase(),
    ),
    ...(startDate ? { startDate } : {}),
    ...(endDate ? { endDate } : {}),
    ...(maxTesters ? { maxTesters } : {}),
  }

  const { id } = await serverFetch<ProjectResponse>('projects', {
    method: 'POST',
    body,
  })

  /**
   * Type of testing belongs to the BUILD, not the project.
   *
   * `POST /projects` creates the project and one default build; `testType` is
   * a field on that build, so it takes a second call — the same three-step
   * the customer wizard does. The build id is not in the create response
   * (`projectSelect` has no builds), hence the read in between.
   *
   * Best-effort, and deliberately so: if this fails the project still exists
   * and its type can be set from Build details. Losing a whole project over
   * one optional field would be the worse outcome, so the redirect happens
   * either way and carries a notice when the type did not stick.
   */
  const testType = formTrimmed(formData, 'testType')
  let notice = ''
  if (testType) {
    try {
      const detail = await serverFetch<ProjectBuilds>(`projects/${id}`)
      const buildId = detail.builds?.find((b) => b.isDefault)?.id ?? detail.builds?.[0]?.id
      if (!buildId) throw new Error('no build on the new project')
      await serverFetch(`projects/${id}/builds/${buildId}`, {
        method: 'PATCH',
        body: { testType },
      })
    } catch {
      notice = '?notice=test-type-unset'
    }
  }

  revalidatePath('/app/admin/projects')
  redirect(`/app/admin/projects/${id}${notice}`)
}
