import { DetailShell } from '@/components/admin/DetailShell'
import { Panel } from '@/components/admin/Panel'
import { Button } from '@/components/ds/core/Button'
import { Field } from '@/components/ds/forms/Field'
import { Input } from '@/components/ds/forms/Input'
import { Select } from '@/components/ds/forms/Select'
import { Textarea } from '@/components/ds/forms/Textarea'
import { requirePermission } from '@/lib/auth/session'
import { createOrganisationAction } from '@/lib/admin/organisation-actions'
import { titleCase } from '@/lib/admin/format'

/**
 * `/app/admin/organisations/new` — create an organisation on behalf of a
 * customer.
 *
 * The slug is generated by the API from the name, so the form does not ask
 * for one — collecting both lets the two drift apart, and the slug is the
 * URL identifier. The status field defaults to PENDING because a brand-new
 * customer record is not yet ready to be in operation.
 *
 * "Owner user" is optional. An admin who is filling in this form before the
 * customer has an account can leave it blank and invite the owner afterwards
 * from the detail page's Members panel.
 */
const STATUSES = ['PENDING', 'ACTIVE', 'SUSPENDED', 'ARCHIVED'] as const
const STATUS_OPTIONS = STATUSES.map((value) => ({ value, label: titleCase(value) }))

export default async function NewOrganisationPage({
  searchParams,
}: {
  searchParams: Promise<{ error?: string; name?: string }>
}) {
  await requirePermission('organisation.write')

  const params = await searchParams
  const backHref = '/app/admin/organisations'

  return (
    <DetailShell
      crumbs={[
        { label: 'Organisations', href: '/app/admin/organisations' },
        { label: 'New' },
      ]}
      eyebrow="Accounts"
      title="New organisation"
      subtitle="A customer account. The owner, if set, becomes the first member and can manage the rest of the team."
    >
      <Panel
        title="Profile"
        description="The minimum needed to create an organisation. Everything else can be filled in on the detail page."
      >
        {params.error ? (
          <div
            role="alert"
            style={{
              marginBottom: 'var(--space-6)',
              padding: 'var(--space-4) var(--space-5)',
              border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-input)',
              background: 'var(--status-error-bg)',
              color: 'var(--status-error-fg)',
              fontSize: 'var(--type-body-sm-size)',
              lineHeight: 1.45,
            }}
          >
            {params.error === 'duplicate'
              ? "An organisation already uses that email or name. Pick another and try again."
              : "Couldn't create the organisation. Check the form and try again."}
          </div>
        ) : null}
        <form action={createOrganisationAction} style={formStyle}>
          <div style={fieldGrid}>
            <Field label="Name" htmlFor="name" required hint="The legal or trading name shown to the team.">
              <Input id="name" name="name" required defaultValue={params.name ?? ''} />
            </Field>
            <Field
              label="Status"
              htmlFor="status"
              hint="New organisations usually start as PENDING. Switch to ACTIVE after onboarding is complete."
            >
              <Select id="status" name="status" defaultValue="PENDING" options={STATUS_OPTIONS} />
            </Field>
          </div>

          <div style={fieldGrid}>
            <Field label="Industry" htmlFor="industry" hint="Free text — banking, retail, healthcare, etc.">
              <Input id="industry" name="industry" />
            </Field>
            <Field label="Website" htmlFor="website" hint="Full URL, including https://">
              <Input id="website" name="website" type="url" placeholder="https://" />
            </Field>
          </div>

          <div style={fieldGrid}>
            <Field
              label="Contact email"
              htmlFor="contactEmail"
              required
              hint="Used by the platform to reach the customer."
            >
              <Input id="contactEmail" name="contactEmail" type="email" required />
            </Field>
            <Field label="Contact phone" htmlFor="contactPhone">
              <Input id="contactPhone" name="contactPhone" type="tel" />
            </Field>
          </div>

          <Panel
            title="Address"
            description="Optional. Only needed if the platform will send post or print invoices."
          >
            <div style={fieldGrid}>
              <Field label="Address line 1" htmlFor="addressLine1">
                <Input id="addressLine1" name="addressLine1" />
              </Field>
              <Field label="Address line 2" htmlFor="addressLine2">
                <Input id="addressLine2" name="addressLine2" />
              </Field>
            </div>
            <div style={fieldGrid}>
              <Field label="City" htmlFor="city">
                <Input id="city" name="city" />
              </Field>
              <Field label="State / region" htmlFor="state">
                <Input id="state" name="state" />
              </Field>
              <Field label="Postal code" htmlFor="postalCode">
                <Input id="postalCode" name="postalCode" />
              </Field>
              <Field
                label="Country"
                htmlFor="countryCode"
                hint="ISO 3166-1 alpha-2 — IN, US, GB, etc."
              >
                <Input
                  id="countryCode"
                  name="countryCode"
                  maxLength={2}
                  style={{ textTransform: 'uppercase' }}
                />
              </Field>
            </div>
          </Panel>

          <div style={fieldGrid}>
            <Field
              label="Tax ID"
              htmlFor="taxId"
              hint="VAT, GST, EIN — whatever the customer uses. Required for invoicing in some regions."
            >
              <Input id="taxId" name="taxId" />
            </Field>
            <Field
              label="Owner user id"
              htmlFor="ownerUserId"
              hint="Optional. If the account already exists, paste their cuid here to make them the owner."
            >
              <Input id="ownerUserId" name="ownerUserId" placeholder="cmxyz…" />
            </Field>
          </div>

          <Field
            label="Internal notes"
            htmlFor="notes"
            hint="Not visible to the customer. Used by the admin team only."
          >
            <Textarea id="notes" name="notes" rows={4} />
          </Field>

          <div style={{ display: 'flex', gap: 'var(--space-3)' }}>
            <Button type="submit" variant="primary" iconLeft="check">
              Create organisation
            </Button>

            <Button type="button" variant="ghost" href={backHref}>
              Cancel
            </Button>
          </div>
        </form>
      </Panel>
    </DetailShell>
  )
}

const formStyle = {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: 'var(--space-6)',
}

const fieldGrid = {
  display: 'grid',
  gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
  gap: 'var(--space-5) var(--space-6)',
}
