import { ImageResponse } from 'next/og'
import { BRAND_COLORS } from '@/styles/brand'
import { HOME_HERO } from '@/content/home'
import { promises as fs } from 'node:fs'
import { join } from 'node:path'

/**
 * The site-wide Open Graph card, rendered at build time.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WHY THIS FILE REPLACES A STATIC PNG
 *
 * `lib/seo/metadata.ts` pointed every page's `og:image` at `/og/default.png`,
 * which did not exist — so every share on LinkedIn, Slack or X unfurled with a
 * broken image. Generating it means the card cannot rot and stays in step with
 * the tokens.
 *
 * Placed at the app root, so Next uses it as the fallback for every route that
 * does not define its own. Per-page cards can be added later as
 * `opengraph-image.tsx` inside a segment; that is a step-10 refinement, not a
 * blocker.
 *
 * TWO CONSTRAINTS THIS FILE HAS TO RESPECT.
 *
 *  1. It runs in the Edge/OG runtime, NOT the browser. There is no CSS cascade,
 *     no custom properties and no stylesheet — Satori resolves a small subset of
 *     flexbox from inline styles only. That is why the colours are literals from
 *     `styles/brand.ts` rather than `var(--ink-950)`: a custom property here
 *     resolves to nothing and renders a black box.
 *  2. Fonts must be fetched as binary and handed over explicitly. Instrument
 *     Sans is NOT loaded here — `next/font` does not apply in this runtime, and
 *     fetching a webfont at build time on every deploy is a network dependency
 *     for a decorative asset. The card uses the runtime's default sans, which is
 *     close enough at 72px for a share preview. Ship the real face by committing
 *     the .ttf and reading it with `fs` if the difference matters.
 *
 *  3. The mark itself is read from disk at build time and inlined as a data
 *     URL, because Satori cannot fetch by URL. The raster is generated by
 *     `scripts/prepare-og-mark.ts` from `public/logo.svg`, transparentised and
 *     resized to 480×480. ~28 KB after optimisation. The card is 1200×630 so
 *     the mark sits at ~40% of the height and reads cleanly at Twitter card
 *     preview sizes.
 * ──────────────────────────────────────────────────────────────────────────
 */

export const alt = 'Crowd4Test — AI-powered digital quality engineering'
export const size = { width: 1200, height: 630 }
export const contentType = 'image/png'

async function loadMarkDataUrl(): Promise<string> {
  // live edit: the raster sits in `public/og-mark.png` next to the other
  // brand assets. fs.readFile runs at build time, so the data URL is baked
  // into the prerendered HTML rather than fetched at request time.
  try {
    const path = join(process.cwd(), 'public', 'og-mark.png')
    const bytes = await fs.readFile(path)
    return `data:image/png;base64,${bytes.toString('base64')}`
  } catch {
    // The card still renders if the raster is missing — the mark just doesn't
    // appear. Failing silently here would be wrong (no loud signal that the
    // brand asset is broken), so we surface it in the build log instead.
    console.warn('[opengraph-image] public/og-mark.png not found; the card will omit the mark')
    return ''
  }
}

export default async function OpengraphImage() {
  const markSrc = await loadMarkDataUrl()

  return new ImageResponse(
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'stretch',
        // The ink floor and the teal accent, matching the site's dark bands.
        backgroundColor: BRAND_COLORS.ink950,
        padding: 60,
      }}
    >
      {/* The mark on the left. Satori treats the <img> like a positioned bg
            image at the URL given; we use a hard-coded size because the card is
            fixed at 1200×630. The element is empty with no children, so the
            alt text is the only thing announced if a scraper reads the card. */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 480,
          height: 480,
          marginRight: 40,
        }}
      >
        {markSrc ? (
          // <img> is intentional here, not a forgotten <Image>. The OG card runs
          // in the Edge/OG runtime; next/image is not available, and the data
          // URL is inlined into the ImageResponse payload at build time anyway.
          // The src points at a base64 string, not a URL the optimiser could
          // fetch — there is nothing to optimise.
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={markSrc}
            width={480}
            height={480}
            alt="Crowd4Test"
            style={{ width: '100%', height: '100%', objectFit: 'contain' }}
          />
        ) : null}
      </div>

      {/* The copy on the right — eyebrow, headline, tag, exactly as before. */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          flex: 1,
          padding: '20px 0',
        }}
      >
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div
            style={{
              display: 'flex',
              fontSize: 20,
              letterSpacing: 3,
              textTransform: 'uppercase',
              color: BRAND_COLORS.teal100,
              marginBottom: 28,
            }}
          >
            AI-Powered Digital Quality Engineering
          </div>
          <div
            style={{
              display: 'flex',
              fontSize: 64,
              fontWeight: 600,
              lineHeight: 1.05,
              letterSpacing: -2.5,
              color: BRAND_COLORS.ink50,
              maxWidth: 540,
            }}
          >
            {/*
              READ FROM THE CONTENT MODULE, NOT RETYPED.
              This card carried its own copy of the homepage headline, so when
              the Client replaced that headline the social preview kept
              advertising the old one — the link unfurled in Slack or LinkedIn
              with a promise the page no longer made. Bound to HOME_HERO.title
              so the two can no longer drift.
            */}
            {HOME_HERO.title}
          </div>
        </div>

        {/* A hairline, not a border on the container. */}
        <div
          style={{
            display: 'flex',
            borderTop: `1px solid ${BRAND_COLORS.ink800}`,
            paddingTop: 24,
            fontSize: 22,
            color: BRAND_COLORS.ink300,
          }}
        >
          AI agents at machine speed. Human testers for judgment.
        </div>
      </div>
    </div>,
    size,
  )
}
